[配置文件]

[copy_diffrent_country_shop_asin_pic.py] 
#功能
对不同店铺不同国家的图片进行命名，格式：asin.PS01.jpg

[参数配置]
#excel格式
sheet页：'店铺名-国家缩写'
内容： 无表头的纯asin列

#图片
与sheet页中的店铺相匹配的图片，命名格式如 的卢.jpg 杰宝.jpg

#代码更改参数
path： ASIN.xlsx的存放路径，其余不改变




#如有特殊需求，请飞书联系：杨心格